In [1]:
import pandas as pd

In [2]:
nmdc_mongo_slot_usage = pd.read_csv("nmdc.flattened_biosample_field_counts.csv", sep=",")

In [3]:
nmdc_mongo_slot_usage.columns = ['path', 'count']

In [4]:
nmdc_mongo_slot_usage['slot'] = nmdc_mongo_slot_usage['path'].str.replace(r'(_has|_term|_latitude|_longitude).*$', '',
                                                                          regex=True)

In [5]:
nmdc_mongo_slot_usage = nmdc_mongo_slot_usage[['slot', 'count']]

In [6]:
nmdc_mongo_slot_usage = nmdc_mongo_slot_usage.copy()
nmdc_mongo_slot_usage.drop_duplicates(inplace=True)

In [7]:
nmdc_mongo_slot_usage = nmdc_mongo_slot_usage[nmdc_mongo_slot_usage['slot'] != '_id']

In [8]:
nmdc_mongo_slot_usage = nmdc_mongo_slot_usage.loc[nmdc_mongo_slot_usage.groupby("slot")["count"].idxmax()].reset_index(
    drop=True)

In [9]:
nmdc_mongo_slot_usage = nmdc_mongo_slot_usage.sort_values(by=['count', 'slot'], ascending=[False, True])

In [10]:
nmdc_mongo_slot_usage

                   slot  count
8    associated_studies  13006
36      env_broad_scale  13006
37      env_local_scale  13006
38           env_medium  13006
61                   id  13006
..                  ...    ...
27            diss_iron      6
90     samp_mat_process      6
99               sodium      6
110             sulfate      6
109    subsurface_depth      1

[122 rows x 2 columns]

In [11]:
nmdc_submission_slot_usage = pd.read_csv("misc_metadata.submission_biosample_slot_counts.csv", sep=",")

In [12]:
nmdc_submission_slot_usage.drop(columns=["_id"], inplace=True)

In [13]:
nmdc_submission_slot_usage = nmdc_submission_slot_usage[['field', 'count']]

In [14]:
nmdc_submission_slot_usage.columns = ['slot', 'count']

In [15]:
nmdc_submission_slot_usage = nmdc_submission_slot_usage.sort_values(by=['count', 'slot'], ascending=[False, True])

In [16]:
nmdc_submission_slot_usage

                    slot  count
28             samp_name  20626
44         analysis_type  19366
174      collection_date  16462
34               lat_lon  16459
137         geo_loc_name  16420
..                   ...    ...
113       technical_reps      3
91      ventilation_type      3
133            biol_stat      1
97   cur_vegetation_meth      1
53          size_frac_up      1

[178 rows x 2 columns]

In [17]:
exploded_mixs_preferred_units = pd.read_csv("exploded_mixs_preferred_units.tsv", sep="\t")

In [18]:
exploded_mixs_preferred_units

,slot,value,split,UCUM,confidence,notes
0,host_common_name,NaN,NaN,10.L/min,low,Partial match on UCUM description
1,samp_name,NaN,NaN,10.L/min,low,Partial match on UCUM description
2,light_regm,"lux; micrometer, nanometer, angstrom",angstrom,NaN,none,No match found
3,pressure,atmosphere,atmosphere,atm,high,Exact match on UCUM description
4,hcr_pressure,"atmosphere, kilopascal",atmosphere,atm,high,Exact match on UCUM description
...,...,...,...,...,...,...
376,floor_age,"years, weeks, days",weeks,NaN,none,No match found
377,built_struc_age,year,year,a,high,Exact match on UCUM description
378,host_age,"year, day, hour",year,a,high,Exact match on UCUM description
379,association_duration,"year, day, hour",year,a,high,Exact match on UCUM description
380,floor_age,"years, weeks, days",years,NaN,none,No match found

In [19]:
nmdc_mongo_slots_mixs_prefunits_ucum = nmdc_mongo_slot_usage.merge(exploded_mixs_preferred_units, how='outer')

In [20]:
nmdc_mongo_slots_mixs_prefunits_ucum

,slot,count,value,split,UCUM,confidence,notes
0,abs_air_humidity,192.0,"gram per gram, kilogram per kilogram, kilogram...",gram per gram,g/g,high,Exact match on UCUM description
1,abs_air_humidity,192.0,"gram per gram, kilogram per kilogram, kilogram...",kilogram,kg,high,Exact match on UCUM description
2,abs_air_humidity,192.0,"gram per gram, kilogram per kilogram, kilogram...",kilogram per kilogram,NaN,none,No match found
3,abs_air_humidity,192.0,"gram per gram, kilogram per kilogram, kilogram...",pound,[lb_av],low,Partial match on UCUM description
4,add_date,2637.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
459,window_size,NaN,"inch, meter",inch,[cin_i],low,Partial match on UCUM description
460,window_size,NaN,"inch, meter",meter,m,high,Exact match on UCUM description
461,xylene,NaN,"milligram per liter, parts per million",milligram per liter,mg/L,high,Exact match on UCUM description
462,xylene,NaN,"milligram per liter, parts per million",parts per million,NaN,none,No match found
463,zinc,103.0,NaN,NaN,NaN,NaN,NaN

In [21]:
nmdc_mongo_slots_mixs_prefunits_ucum.to_csv("nmdc_mongo_slots_mixs_prefunits_ucum.tsv", sep="\t", index=False)

In [22]:
nmdc_submission_slots_mixs_prefunits_ucum = nmdc_submission_slot_usage.merge(exploded_mixs_preferred_units, how='outer')

In [23]:
nmdc_submission_slots_mixs_prefunits_ucum

,slot,count,value,split,UCUM,confidence,notes
0,abs_air_humidity,NaN,"gram per gram, kilogram per kilogram, kilogram...",gram per gram,g/g,high,Exact match on UCUM description
1,abs_air_humidity,NaN,"gram per gram, kilogram per kilogram, kilogram...",kilogram,kg,high,Exact match on UCUM description
2,abs_air_humidity,NaN,"gram per gram, kilogram per kilogram, kilogram...",kilogram per kilogram,NaN,none,No match found
3,abs_air_humidity,NaN,"gram per gram, kilogram per kilogram, kilogram...",pound,[lb_av],low,Partial match on UCUM description
4,agrochem_addition,2825.0,"gram, mole per liter, milligram per liter",gram,g,high,Exact match on UCUM description
...,...,...,...,...,...,...,...
507,wind_speed,19.0,NaN,NaN,NaN,NaN,NaN
508,window_size,NaN,"inch, meter",inch,[cin_i],low,Partial match on UCUM description
509,window_size,NaN,"inch, meter",meter,m,high,Exact match on UCUM description
510,xylene,NaN,"milligram per liter, parts per million",milligram per liter,mg/L,high,Exact match on UCUM description
511,xylene,NaN,"milligram per liter, parts per million",parts per million,NaN,none,No match found

In [24]:
nmdc_submission_slots_mixs_prefunits_ucum.to_csv("nmdc_submission_slots_mixs_prefunits_ucum.tsv", sep="\t", index=False)